version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=school_user
      - POSTGRESQL_PASSWORD=school_pass
      - POSTGRESQL_DATABASE=school_db
